# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 13 Apr 2017 06:42:06 +0000
*               @ALL          1
*               @user         8
