<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 14 Apr 2017 08:42:43 +0200
 */

$conf['title'] = 'CRA Wiki';
$conf['lang'] = 'zh';
$conf['template'] = 'bootstrap3';
$conf['useheading'] = 'navigation';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['sepchar'] = '-';
$conf['fnencode'] = 'utf-8';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'paper';
$conf['tpl']['bootstrap3']['sidebarShowPageTitle'] = 0;
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = 1;
$conf['tpl']['bootstrap3']['browserTitle'] = '@TITLE@ - CRA Wiki';

// end auto-generated content
